version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      pion-dependencies:
        patterns:
          - "github.com/pion/*"
        update-types:
          - minor
          - patch
      charmbracelet-dependencies:
        patterns:
          - "github.com/charmbracelet/*"
        update-types:
          - minor
          - patch
      golang-x-dependencies:
        patterns:
          - "golang.org/x/*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
